/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/* 
 * File:   Cli_TAB_Variant.h
 * Author: mike
 *
 * Created on July 22, 2020, 8:49 AM
 */

#ifndef CLI_TAB_VARIANT_H
#define CLI_TAB_VARIANT_H

enum Cli_TAB_Variant {
    CLI_TAB_VARIANT_EMPTY_STRING,



    CLI_TAB_VARIANT_NO_ENTER_NO_LOG_NO_ADD_NO_SPACE,
    CLI_TAB_VARIANT_NO_ENTER_NO_LOG_NO_ADD_SPACE,
    CLI_TAB_VARIANT_NO_ENTER_NO_LOG_1_ADD_NO_SPACE,
    CLI_TAB_VARIANT_NO_ENTER_NO_LOG_1_ADD_SPACE,
    CLI_TAB_VARIANT_NO_ENTER_NO_LOG_2_ADD_NO_SPACE,
    CLI_TAB_VARIANT_NO_ENTER_NO_LOG_2_ADD_SPACE,

    CLI_TAB_VARIANT_NO_ENTER_1_LOG_NO_ADD_NO_SPACE,
    CLI_TAB_VARIANT_NO_ENTER_1_LOG_NO_ADD_SPACE,
    CLI_TAB_VARIANT_NO_ENTER_1_LOG_1_ADD_NO_SPACE,
    CLI_TAB_VARIANT_NO_ENTER_1_LOG_1_ADD_SPACE,
    CLI_TAB_VARIANT_NO_ENTER_1_LOG_2_ADD_NO_SPACE,
    CLI_TAB_VARIANT_NO_ENTER_1_LOG_2_ADD_SPACE,

    CLI_TAB_VARIANT_NO_ENTER_2_LOG_NO_ADD_NO_SPACE,
    CLI_TAB_VARIANT_NO_ENTER_2_LOG_NO_ADD_SPACE,
    CLI_TAB_VARIANT_NO_ENTER_2_LOG_1_ADD_NO_SPACE,
    CLI_TAB_VARIANT_NO_ENTER_2_LOG_1_ADD_SPACE,
    CLI_TAB_VARIANT_NO_ENTER_2_LOG_2_ADD_NO_SPACE,
    CLI_TAB_VARIANT_NO_ENTER_2_LOG_2_ADD_SPACE,



    CLI_TAB_VARIANT_ENTER_NO_LOG_NO_ADD_NO_SPACE,
    CLI_TAB_VARIANT_ENTER_NO_LOG_NO_ADD_SPACE,
    CLI_TAB_VARIANT_ENTER_NO_LOG_1_ADD_NO_SPACE,
    CLI_TAB_VARIANT_ENTER_NO_LOG_1_ADD_SPACE,
    CLI_TAB_VARIANT_ENTER_NO_LOG_2_ADD_NO_SPACE,
    CLI_TAB_VARIANT_ENTER_NO_LOG_2_ADD_SPACE,

    CLI_TAB_VARIANT_ENTER_1_LOG_NO_ADD_NO_SPACE,
    CLI_TAB_VARIANT_ENTER_1_LOG_NO_ADD_SPACE,
    CLI_TAB_VARIANT_ENTER_1_LOG_1_ADD_NO_SPACE,
    CLI_TAB_VARIANT_ENTER_1_LOG_1_ADD_SPACE,
    CLI_TAB_VARIANT_ENTER_1_LOG_2_ADD_NO_SPACE,
    CLI_TAB_VARIANT_ENTER_1_LOG_2_ADD_SPACE,

    CLI_TAB_VARIANT_ENTER_2_LOG_NO_ADD_NO_SPACE,
    CLI_TAB_VARIANT_ENTER_2_LOG_NO_ADD_SPACE,
    CLI_TAB_VARIANT_ENTER_2_LOG_1_ADD_NO_SPACE,
    CLI_TAB_VARIANT_ENTER_2_LOG_1_ADD_SPACE,
    CLI_TAB_VARIANT_ENTER_2_LOG_2_ADD_NO_SPACE,
    CLI_TAB_VARIANT_ENTER_2_LOG_2_ADD_SPACE,



};

#endif /* CLI_TAB_VARIANT_H */
