
cat test_check_00_header > t

cat test_check_01 >> t
cat test_check_02 >> t
cat test_check_03 >> t
cat test_check_04 >> t
cat test_check_05 >> t
cat test_check_06 >> t
cat test_check_07 >> t
cat test_check_08 >> t
cat test_check_09 >> t
cat test_check_10 >> t
cat test_check_11 >> t
cat test_check_12 >> t
cat test_check_13 >> t
cat test_check_14 >> t
cat test_check_15 >> t
cat test_check_16 >> t
cat test_check_17 >> t
cat test_check_18 >> t
cat test_check_19 >> t
cat test_check_20 >> t
cat test_check_21 >> t
cat test_check_22 >> t
cat test_check_23 >> t
cat test_check_24 >> t
cat test_check_25 >> t
cat test_check_26 >> t
cat test_check_27 >> t
cat test_check_28 >> t
cat test_check_29 >> t
cat test_check_30 >> t
cat test_check_31 >> t
cat test_check_32 >> t
cat test_check_33 >> t
cat test_check_34 >> t
cat test_check_35 >> t
cat test_check_36 >> t
cat test_check_37 >> t
cat test_check_38 >> t
cat test_check_39 >> t
cat test_check_40 >> t
cat test_check_41 >> t
cat test_check_42 >> t
cat test_check_43 >> t
cat test_check_44 >> t
cat test_check_45 >> t
cat test_check_46 >> t
cat test_check_47 >> t
cat test_check_48 >> t
cat test_check_49 >> t

cat test_check_99_footer >> t
