namespace Cli_Core_CS
{
    enum Cmd_Token_Parser_Char_Type
    {
        CMD_TOKEN_PARSER_CHAR_TYPE_NO,

        CMD_TOKEN_PARSER_CHAR_TYPE_SPACE,
        CMD_TOKEN_PARSER_CHAR_TYPE_NEWLINE,
        CMD_TOKEN_PARSER_CHAR_TYPE_ALPHA,
        CMD_TOKEN_PARSER_CHAR_TYPE_DIGIT,

        CMD_TOKEN_PARSER_CHAR_TYPE_COMMAS,

        CMD_TOKEN_PARSER_CHAR_TYPE_POINT,

        CMD_TOKEN_PARSER_CHAR_TYPE_ERROR,

        CMD_TOKEN_PARSER_CHAR_TYPE_LAST,
        CMD_TOKEN_PARSER_CHAR_TYPE_UNDEFINED
    }
}
