
cat test_check_00_header > test_check

cat test_check_01 >> test_check
cat test_check_02 >> test_check
cat test_check_03 >> test_check
cat test_check_04 >> test_check
cat test_check_05 >> test_check
cat test_check_06 >> test_check
cat test_check_07 >> test_check
cat test_check_08 >> test_check
cat test_check_09 >> test_check
cat test_check_10 >> test_check
cat test_check_11 >> test_check
cat test_check_12 >> test_check
cat test_check_13 >> test_check
cat test_check_14 >> test_check
cat test_check_15 >> test_check
cat test_check_16 >> test_check
cat test_check_17 >> test_check
cat test_check_18 >> test_check
cat test_check_19 >> test_check
cat test_check_20 >> test_check
cat test_check_21 >> test_check
cat test_check_22 >> test_check
cat test_check_23 >> test_check
cat test_check_24 >> test_check
cat test_check_25 >> test_check
cat test_check_26 >> test_check
cat test_check_27 >> test_check
cat test_check_28 >> test_check
cat test_check_29 >> test_check
cat test_check_30 >> test_check
cat test_check_31 >> test_check
cat test_check_32 >> test_check
cat test_check_33 >> test_check
cat test_check_34 >> test_check
cat test_check_35 >> test_check
cat test_check_36 >> test_check
cat test_check_37 >> test_check
cat test_check_38 >> test_check
cat test_check_39 >> test_check
cat test_check_40 >> test_check
cat test_check_41 >> test_check
cat test_check_42 >> test_check
cat test_check_43 >> test_check
cat test_check_44 >> test_check
cat test_check_45 >> test_check
cat test_check_46 >> test_check
cat test_check_47 >> test_check
cat test_check_48 >> test_check
cat test_check_49 >> test_check

cat test_check_99_footer >> test_check
